module.exports = {
  apps: [
    {
      name: 'simple-api',
      cwd: './simple-api',
      script: 'index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '~/.pm2/logs/simple-api-error.log',
      out_file: '~/.pm2/logs/simple-api-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'arena-admin',
      cwd: './apps/web-admin',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '~/.pm2/logs/arena-admin-error.log',
      out_file: '~/.pm2/logs/arena-admin-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'arena-studio',
      cwd: './apps/web-studio',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: '~/.pm2/logs/arena-studio-error.log',
      out_file: '~/.pm2/logs/arena-studio-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'arena-player',
      cwd: './apps/web-player',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: '~/.pm2/logs/arena-player-error.log',
      out_file: '~/.pm2/logs/arena-player-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'arena-screen',
      cwd: './apps/web-screen',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: '~/.pm2/logs/arena-screen-error.log',
      out_file: '~/.pm2/logs/arena-screen-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
  ],
};
